[toolchain]
channel = "nightly-2026-01-22" # clippy_utils depends on this specific version
profile = "default"
components = ["llvm-tools-preview", "rustc-dev", "rust-src"] # components are additive with profile
